# compiler:
#  - clang
#  - gcc

#script:
#  - make MODE=dbg VALGRIND=on test
#  - make MODE=opt test
#  - make

install:
  - sudo apt-get install valgrind

matrix:
  include:
    - language: c
      compiler: gcc
      script: make MODE=opt test
    - language: c
      compiler: clang
      script: make MODE=opt test
