# The default build. It really makes no difference which target is the default
# and which are defined though the build matrix.
language: c
compiler: gcc
script: ./configure --noisy && ./build.sh run-tests
before_install: git submodule update --init --recursive
install: source ./tools/enter-devenv.sh
sudo: false
addons:
  apt:
    packages:
    - python-virtualenv

matrix:
  include:
    # Test a clang build in debug mode under valgrind.
    - language: c
      compiler: clang
      script: ./configure --debug --valgrind --noisy && ./build.sh run-tests
      before_install: git submodule update --init --recursive
      install: source ./tools/enter-devenv.sh
      addons:
        apt:
          packages:
          - python-virtualenv
          - valgrind
    # Test a debug build with expensive checks but not under valgrind.
    - language: c
      compiler: clang
      script: ./configure --debug --expchecks --noisy && ./build.sh run-ctrino-tests
      before_install: git submodule update --init --recursive
      install: source ./tools/enter-devenv.sh
    # Test everything using an optimized clang build.
    - language: c
      compiler: clang
      script: ./configure --noisy && ./build.sh run-ctrino-tests
      before_install: git submodule update --init --recursive
      install: source ./tools/enter-devenv.sh
    # Test with checks disabled.
    - languate: c
      compiler: clang
      script: ./configure --nochecks --noisy && ./build.sh run-ctrino-tests
      before_install: git submodule update --init --recursive
      install: source ./tools/enter-devenv.sh
    # Check that the C code compiles using gcc.
    - language: c
      compiler: gcc
      script: ./configure --debug --noisy && ./build.sh run-ctrino-tests
      before_install: git submodule update --init --recursive
      install: source ./tools/enter-devenv.sh
